[features]
seeds = false
skip-lint = false
[programs.devnet]
otc_market = "n44B2i7iW7txBg3JqHrJPaeiF83b2jk95SHg28SutyW"

[programs.localnet]
otc_market = "8zRqCPWhABbGvGB7koR5D8ffgV7Q4w564ye9tw16pPc6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
