[features]
seeds = false
skip-lint = false
[programs.devnet]
otc_market = "TwPdCz6GC42QEYgMkvHhBabVMFHe4hwQuqRRkCq6hai"

[programs.localnet]
otc_market = "8zRqCPWhABbGvGB7koR5D8ffgV7Q4w564ye9tw16pPc6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/jusikx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
